### ISSUE TITLE
Linter crashes on `getValueMappings` for  `rule_panel_units`

### ISSUE THREAD

**Issue by di3go-sona** [grafana/dashboard-linter#210]
The linter fails with the following error despite the dashboard being valid for grafana [trinityx-prometheus-home-sample.json](https://github.com/user-attachments/files/17774415/trinityx-prometheus-home-sample.json)

```
panic: interface conversion: interface {} is []interface {}, not []dashboard.ValueMapOrRangeMapOrRegexMapOrSpecialValueMap

goroutine 1 [running]:
github.com/grafana/dashboard-linter/lint.getValueMappings(...)
        /root/go/pkg/mod/github.com/grafana/dashboard-linter@v0.0.0-20241106223805-1e7999311752/lint/rule_panel_units.go:136
github.com/grafana/dashboard-linter/lint.NewPanelUnitsRule.func1({{0x0, 0x0, 0x0}, {0xc00055507c, 0x4}, {{0xc0001dc780, 0x3, 0x4}}, {{0xc000459520, 0x1, ...}}, ...}, ...)
        /root/go/pkg/mod/github.com/grafana/dashboard-linter@v0.0.0-20241106223805-1e7999311752/lint/rule_panel_units.go:92 +0x6c7
github.com/grafana/dashboard-linter/lint.PanelRuleFunc.Lint({{0x14cd3f7, 0x10}, {0x1505787, 0x34}, 0xc000459960}, {{0x0, 0x0, 0x0}, {0xc00055507c, 0x4}, ...}, ...)
        /root/go/pkg/mod/github.com/grafana/dashboard-linter@v0.0.0-20241106223805-1e7999311752/lint/rules.go:69 +0x255
github.com/grafana/dashboard-linter/lint.(*RuleSet).Lint(0xc0005bf968, {0xc0005bfac0, 0x1, 0xc00055507c?})
        /root/go/pkg/mod/github.com/grafana/dashboard-linter@v0.0.0-20241106223805-1e7999311752/lint/rules.go:209 +0x11d
main.glob..func2(0xc0000bcb00?, {0xc0004594c0?, 0x1?, 0x14be4f2?})
        /root/go/pkg/mod/github.com/grafana/dashboard-linter@v0.0.0-20241106223805-1e7999311752/main.go:73 +0x49c
github.com/spf13/cobra.(*Command).execute(0x223c9a0, {0xc0004594a0, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x223cf60)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
        /root/go/pkg/mod/github.com/grafana/dashboard-linter@v0.0.0-20241106223805-1e7999311752/main.go:176 +0x1a
```

The issue seems to be related to units and overrides, I attached a s[trinityx-prometheus-home-sample.json](https://github.com/user-attachments/files/17774418/trinityx-prometheus-home-sample.json)
ample dashboard that fails on lines 114-129 to reproduce the error

**Comment by v-zhuravlev** [comment]
Fixed in https://github.com/grafana/dashboard-linter/pull/218
